version: "3"

services:
    front:
        build:
            context: .
            dockerfile: Dockerfile.front
        restart: always
        volumes:
            - './front:/app'
            - '/app/node_modules'
        networks:
            - twebapp
        ports:
            - '30001:3000'
        environment:
            - NODE_ENV=development

    back:
        image: node:12
        restart: always
        volumes:
            - ./back:/usr/src/app
            - /usr/src/app/node_modules
        working_dir: /usr/src/app
        networks:
            - twebapp
        ports:
            - "42001:4200"
        command: bash -c "npm install && npm run start"

    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        networks:
            - twebapp
        ports:
            - "54321:5432"
        volumes:
            - /var/lib/postgresql/data
            - ./SQL:/docker-entrypoint-initdb.d

networks:
    twebapp:
