version: "3"

services:
    back:
        image: node:12
        volumes:
            - ./back:/usr/src/app
            - /usr/src/app/node_modules
        working_dir: /usr/src/app
        networks:
            - twebapp
        ports:
            - "42001:4200"
        command: bash -c "npm install && npm run start"

    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        networks:
            - twebapp
        ports:
            - "54321:5432"
        volumes:
            - ./SQL:/docker-entrypoint-initdb.d

networks:
    twebapp:
